module.exports = {
    version: require('../package.json').version,

    AllocationManager: require('./managers/AllocationManager'),
    ApplicationRequestManager: require('./application/ApplicationRequestManager'),
    ApplicationServerManager: require('./application/ApplicationServerManager'),
    ApplicationServer: require('./structures/ApplicationServer'),
    BackupManager: require('./client/BackupManager'),
    BaseUser: require('./structures/User').BaseUser,
    ClientRequestManager: require('./client/ClientRequestManager'),
    ClientServer: require('./structures/ClientServer'),
    ClientServerManager: require('./client/ClientServerManager'),
    ClientUser: require('./structures/User').ClientUser,
    DatabaseManager: require('./managers/DatabaseManager'),
    Dict: require('./structures/Dict'),
    Errors: require('./structures/Errors'),
    FileManager: require('./managers/FileManager'),
    Node: require('./structures/Node'),
    NodeLocationManager: require('./application/NodeLocationManager'),
    NodeManager: require('./application/NestManager'),
    Permissions: require('./structures/Permissions'),
    Presets: require('./structures/Presets'),
    PteroApp: require('./application/PteroApp'),
    PteroClient: require('./client/PteroClient'),
    PteroSubUser: require('./structures/User').PteroSubUser,
    PteroUser: require('./structures/User').PteroUser,
    Schedule: require('./structures/Schedule'),
    SubUserManager: require('./client/SubUserManager'),
    UserManager: require('./application/UserManager'),

    NodeStatus: require('./extensions/NodeStatus')
};
